- name: install httpd package
  yum:
   name: httpd
   state: present
  become: yes
  when: ansible_distribution == "CentOS" 
- name: start httpd service
  tags: http_start
  service:
   name: httpd
   state: started
   enabled: yes
  become: yes


